#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : upower
Version  : 0.99.14
Release  : 26
URL      : https://gitlab.freedesktop.org/upower/upower/-/archive/v0.99.14/upower-v0.99.14.tar.gz
Source0  : https://gitlab.freedesktop.org/upower/upower/-/archive/v0.99.14/upower-v0.99.14.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: upower-bin = %{version}-%{release}
Requires: upower-data = %{version}-%{release}
Requires: upower-lib = %{version}-%{release}
Requires: upower-libexec = %{version}-%{release}
Requires: upower-license = %{version}-%{release}
Requires: upower-locales = %{version}-%{release}
Requires: upower-services = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : libgudev-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gudev-1.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Support-an-entirely-stateless-configuration.patch
Patch2: assert.patch

%description
===============
UPower
===============
Requirements:
glib-2.0             >= 2.34.0
gio-2.0              >= 2.16.1
gudev-1.0            >= 235    (Linux)
libimobiledevice-1.0 >= 0.9.7  (optional)

%package bin
Summary: bin components for the upower package.
Group: Binaries
Requires: upower-data = %{version}-%{release}
Requires: upower-libexec = %{version}-%{release}
Requires: upower-license = %{version}-%{release}
Requires: upower-services = %{version}-%{release}

%description bin
bin components for the upower package.


%package data
Summary: data components for the upower package.
Group: Data

%description data
data components for the upower package.


%package dev
Summary: dev components for the upower package.
Group: Development
Requires: upower-lib = %{version}-%{release}
Requires: upower-bin = %{version}-%{release}
Requires: upower-data = %{version}-%{release}
Provides: upower-devel = %{version}-%{release}
Requires: upower = %{version}-%{release}

%description dev
dev components for the upower package.


%package lib
Summary: lib components for the upower package.
Group: Libraries
Requires: upower-data = %{version}-%{release}
Requires: upower-libexec = %{version}-%{release}
Requires: upower-license = %{version}-%{release}

%description lib
lib components for the upower package.


%package libexec
Summary: libexec components for the upower package.
Group: Default
Requires: upower-license = %{version}-%{release}

%description libexec
libexec components for the upower package.


%package license
Summary: license components for the upower package.
Group: Default

%description license
license components for the upower package.


%package locales
Summary: locales components for the upower package.
Group: Default

%description locales
locales components for the upower package.


%package services
Summary: services components for the upower package.
Group: Systemd services

%description services
services components for the upower package.


%prep
%setup -q -n upower-v0.99.14
cd %{_builddir}/upower-v0.99.14
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644006887
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dman=false \
-Dgtk-doc=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/upower
cp %{_builddir}/upower-v0.99.14/COPYING %{buildroot}/usr/share/package-licenses/upower/9e010b11705daec7ebf9c01a32d6f09ee444968d
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang upower
## install_append content
mv %{buildroot}/etc/UPower %{buildroot}/usr/share/. && mv %{buildroot}/etc/dbus-1/system.d %{buildroot}/usr/share/dbus-1/. && rmdir %{buildroot}/etc/dbus-1 && rmdir %{buildroot}/etc
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/udev/95-upower-hid.rules
/usr/lib/udev/95-upower-wup.rules

%files bin
%defattr(-,root,root,-)
/usr/bin/upower

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/UPowerGlib-1.0.typelib
/usr/share/UPower/UPower.conf
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.Device.xml
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.KbdBacklight.xml
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.Wakeups.xml
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.xml
/usr/share/dbus-1/system-services/org.freedesktop.UPower.service
/usr/share/dbus-1/system.d/org.freedesktop.UPower.conf
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libupower-glib/up-autocleanups.h
/usr/include/libupower-glib/up-client.h
/usr/include/libupower-glib/up-device.h
/usr/include/libupower-glib/up-history-item.h
/usr/include/libupower-glib/up-stats-item.h
/usr/include/libupower-glib/up-types.h
/usr/include/libupower-glib/up-version.h
/usr/include/libupower-glib/up-wakeup-item.h
/usr/include/libupower-glib/up-wakeups.h
/usr/include/libupower-glib/upower.h
/usr/lib64/libupower-glib.so
/usr/lib64/pkgconfig/upower-glib.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libupower-glib.so.3
/usr/lib64/libupower-glib.so.3.1.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/upowerd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/upower/9e010b11705daec7ebf9c01a32d6f09ee444968d

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/upower.service

%files locales -f upower.lang
%defattr(-,root,root,-)

