#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v24
# autospec commit: a88ffdc
#
Name     : upower
Version  : 1.90.8
Release  : 36
URL      : https://gitlab.freedesktop.org/upower/upower/-/archive/v1.90.8/upower-v1.90.8.tar.gz
Source0  : https://gitlab.freedesktop.org/upower/upower/-/archive/v1.90.8/upower-v1.90.8.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: upower-bin = %{version}-%{release}
Requires: upower-config = %{version}-%{release}
Requires: upower-data = %{version}-%{release}
Requires: upower-lib = %{version}-%{release}
Requires: upower-libexec = %{version}-%{release}
Requires: upower-license = %{version}-%{release}
Requires: upower-locales = %{version}-%{release}
Requires: upower-services = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : libgudev-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : polkit-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Support-an-entirely-stateless-configuration.patch
Patch2: assert.patch

%description
# UPower
Requirements:
```text
glib-2.0             >= 2.66.0
gio-2.0              >= 2.16.1
gudev-1.0            >= 235    (Linux)
libimobiledevice-1.0 >= 0.9.7  (optional)
polkit-gobject-1     >= 124
```

%package bin
Summary: bin components for the upower package.
Group: Binaries
Requires: upower-data = %{version}-%{release}
Requires: upower-libexec = %{version}-%{release}
Requires: upower-config = %{version}-%{release}
Requires: upower-license = %{version}-%{release}
Requires: upower-services = %{version}-%{release}

%description bin
bin components for the upower package.


%package config
Summary: config components for the upower package.
Group: Default

%description config
config components for the upower package.


%package data
Summary: data components for the upower package.
Group: Data

%description data
data components for the upower package.


%package dev
Summary: dev components for the upower package.
Group: Development
Requires: upower-lib = %{version}-%{release}
Requires: upower-bin = %{version}-%{release}
Requires: upower-data = %{version}-%{release}
Provides: upower-devel = %{version}-%{release}
Requires: upower = %{version}-%{release}

%description dev
dev components for the upower package.


%package lib
Summary: lib components for the upower package.
Group: Libraries
Requires: upower-data = %{version}-%{release}
Requires: upower-libexec = %{version}-%{release}
Requires: upower-license = %{version}-%{release}

%description lib
lib components for the upower package.


%package libexec
Summary: libexec components for the upower package.
Group: Default
Requires: upower-config = %{version}-%{release}
Requires: upower-license = %{version}-%{release}

%description libexec
libexec components for the upower package.


%package license
Summary: license components for the upower package.
Group: Default

%description license
license components for the upower package.


%package locales
Summary: locales components for the upower package.
Group: Default

%description locales
locales components for the upower package.


%package services
Summary: services components for the upower package.
Group: Systemd services
Requires: systemd

%description services
services components for the upower package.


%package tests
Summary: tests components for the upower package.
Group: Default
Requires: upower = %{version}-%{release}

%description tests
tests components for the upower package.


%prep
%setup -q -n upower-v1.90.8
cd %{_builddir}/upower-v1.90.8
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a upower-v1.90.8 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744142804
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dman=false \
-Dgtk-doc=false  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dman=false \
-Dgtk-doc=false  builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/upower
cp %{_builddir}/upower-v%{version}/COPYING %{buildroot}/usr/share/package-licenses/upower/9e010b11705daec7ebf9c01a32d6f09ee444968d || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang upower
## install_append content
mv %{buildroot}/etc/UPower %{buildroot}/usr/share/. && mv %{buildroot}/etc/dbus-1/system.d %{buildroot}/usr/share/dbus-1/. && rmdir %{buildroot}/etc/dbus-1 && rmdir %{buildroot}/etc
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/upower
/usr/bin/upower

%files config
%defattr(-,root,root,-)
/usr/lib/udev/hwdb.d/60-upower-battery.hwdb
/usr/lib/udev/hwdb.d/95-upower-hid.hwdb
/usr/lib/udev/rules.d/60-upower-battery.rules
/usr/lib/udev/rules.d/95-upower-hid.rules
/usr/lib/udev/rules.d/95-upower-wup.rules

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/UPowerGlib-1.0.typelib
/usr/share/UPower/UPower.conf
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.Device.xml
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.KbdBacklight.xml
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.xml
/usr/share/dbus-1/system-services/org.freedesktop.UPower.service
/usr/share/dbus-1/system.d/org.freedesktop.UPower.conf
/usr/share/gir-1.0/*.gir
/usr/share/polkit-1/actions/org.freedesktop.upower.policy
/usr/share/zsh/site-functions/_upower

%files dev
%defattr(-,root,root,-)
/usr/include/libupower-glib/up-autocleanups.h
/usr/include/libupower-glib/up-client.h
/usr/include/libupower-glib/up-device.h
/usr/include/libupower-glib/up-history-item.h
/usr/include/libupower-glib/up-stats-item.h
/usr/include/libupower-glib/up-types.h
/usr/include/libupower-glib/up-version.h
/usr/include/libupower-glib/upower.h
/usr/lib64/libupower-glib.so
/usr/lib64/pkgconfig/upower-glib.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libupower-glib.so.3.1.0
/usr/lib64/libupower-glib.so.3
/usr/lib64/libupower-glib.so.3.1.0

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/upowerd
/usr/libexec/upower/integration-test.py
/usr/libexec/upower/output_checker.py
/usr/libexec/upower/tests/logitech-g903.device
/usr/libexec/upower/tests/steelseries-headset.device
/usr/libexec/upower/tests/usb-headset.device
/usr/libexec/upower/tests/wacom-bluetooth-active.device
/usr/libexec/upower/tests/wacom-dongle-active.device
/usr/libexec/upower/tests/wacom-dongle-waiting.device
/usr/libexec/upower/tests/wacom-pen-digitiser.device
/usr/libexec/upowerd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/upower/9e010b11705daec7ebf9c01a32d6f09ee444968d

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/upower.service

%files tests
%defattr(-,root,root,-)
/usr/share/installed-tests/upower/upower-integration.test

%files locales -f upower.lang
%defattr(-,root,root,-)

