#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : upower
Version  : 0.99.4
Release  : 1
URL      : https://upower.freedesktop.org/releases/upower-0.99.4.tar.xz
Source0  : https://upower.freedesktop.org/releases/upower-0.99.4.tar.xz
Summary  : UPower is a system daemon for managing power devices
Group    : Development/Tools
License  : GPL-2.0
Requires: upower-bin
Requires: upower-lib
Requires: upower-data
Requires: upower-locales
Requires: upower-config
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(udev)
BuildRequires : systemd-dev

%description
===============
UPower
===============
Requirements:
glib-2.0         >= 2.6.0
gio-2.0          >= 2.16.1
dbus-1           >= 1.0
dbus-glib-1      >= 0.76
gudev-1.0        >= 001
libusb

%package bin
Summary: bin components for the upower package.
Group: Binaries
Requires: upower-data
Requires: upower-config

%description bin
bin components for the upower package.


%package config
Summary: config components for the upower package.
Group: Default

%description config
config components for the upower package.


%package data
Summary: data components for the upower package.
Group: Data

%description data
data components for the upower package.


%package dev
Summary: dev components for the upower package.
Group: Development
Requires: upower-lib
Requires: upower-bin
Requires: upower-data
Provides: upower-devel

%description dev
dev components for the upower package.


%package lib
Summary: lib components for the upower package.
Group: Libraries
Requires: upower-data
Requires: upower-config

%description lib
lib components for the upower package.


%package locales
Summary: locales components for the upower package.
Group: Default

%description locales
locales components for the upower package.


%prep
%setup -q -n upower-0.99.4

%build
%configure --disable-static --disable-man-pages
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
%find_lang upower

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/upower
/usr/libexec/upowerd

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/upower.service
/usr/lib/udev/rules.d/95-upower-csr.rules
/usr/lib/udev/rules.d/95-upower-hid.rules
/usr/lib/udev/rules.d/95-upower-wup.rules

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.Device.xml
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.KbdBacklight.xml
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.Wakeups.xml
/usr/share/dbus-1/interfaces/org.freedesktop.UPower.xml
/usr/share/dbus-1/system-services/org.freedesktop.UPower.service

%files dev
%defattr(-,root,root,-)
/usr/include/libupower-glib/up-autocleanups.h
/usr/include/libupower-glib/up-client.h
/usr/include/libupower-glib/up-device.h
/usr/include/libupower-glib/up-history-item.h
/usr/include/libupower-glib/up-stats-item.h
/usr/include/libupower-glib/up-types.h
/usr/include/libupower-glib/up-version.h
/usr/include/libupower-glib/up-wakeup-item.h
/usr/include/libupower-glib/up-wakeups.h
/usr/include/libupower-glib/upower.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f upower.lang 
%defattr(-,root,root,-)

